# English-language settings.
# babelquarto loads this file automatically when rendering the English (main) pages,
# and anything here is merged with _quarto.yml for those pages.

website:
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research/research.qmd
      - text: "Team"
        menu:
          - text: "PI | Audrey"
            href: team/PI/PI.qmd
          - text: "Members"
            href: team/members/members.qmd
      - text: "Publications"
        href: publications/publications.qmd
      - text: "Educational Resources"
        href: ressources/ressources.qmd
